### ISSUE TITLE
Test issues

### ISSUE THREAD

**Issue by chrissrogers** [duojs/sass#7] opened 2015-03-03 22:46 UTC
- [node 0.12 travis tests](https://travis-ci.org/duojs/sass/jobs/51644025) fail around [duo-css-compat's anonymous generator](https://github.com/duojs/css-compat/blob/a4d4b04398796c28f788c456f8e28382204f9189/index.js#L31) syntax barf. That syntax looks like it's causing the issue, but I am not familiar enough with co to give a proper diagnosis.
- iojs fails because node-sass is missing its libsass bindings. Perhaps node-sass is not compatible with iojs?

**Comment by kevva** [comment] 2015-03-08 19:48
The first point is a duplicate of https://github.com/duojs/duo/issues/433. And nope, node-sass doesn't work with iojs `>1.2.0` yet (https://github.com/sass/node-sass/issues/740).

**Closed as completed by kevva** 2015-03-08 19:48 UTC
